tests:
  - healthStatus:
      status: Healthy
      message: ""
    inputPath: testdata/kcp_deployment_healthy.yaml
  - healthStatus:
      status: Healthy
      message: ""
    inputPath: testdata/standard_deployment_healthy.yaml
  - healthStatus:
      status: Suspended
      message: "Deployment is paused"
    inputPath: testdata/kcp_deployment_paused.yaml
  - healthStatus:
      status: Suspended
      message: "Deployment is paused"
    inputPath: testdata/standard_deployment_paused.yaml
  - healthStatus:
      status: Degraded
      message: "Deployment test exceeded its progress deadline"
    inputPath: testdata/kcp_deployment_degraded.yaml
  - healthStatus:
      status: Degraded
      message: "Deployment test exceeded its progress deadline"
    inputPath: testdata/standard_deployment_degraded.yaml
  - healthStatus:
      status: Progressing
      message: "Waiting for rollout to finish, 1 old replicas are pending termination"
    inputPath: testdata/kcp_deployment_progressing.yaml
  - healthStatus:
      status: Progressing
      message: "Waiting for rollout to finish, 2/4 replicas updated"
    inputPath: testdata/standard_deployment_progressing.yaml
  - healthStatus:
      status: Unknown
      message: "<string>210 status not found"
    inputPath: testdata/kcp_deployment_unknown.yaml
  - healthStatus:
      status: Unknown
      message: "<string>186 attempt to index a non-table object(nil) with key 'paused'"
    inputPath: testdata/kcp_deployment_catch_error.yaml
