apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.12

patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/8
        value: {"name":"plugins","hostPath":{"path":"/tmp/argocd-plugin-sockets"}}
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
    patch: |-
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
      data:
        policy.default: role:admin

