apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.12
  # - https://github.com/argoproj/argo-cd/notifications_catalog/install.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
    patch: |-
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
      data:
        policy.default: role:admin

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - url=config/url
      - resource.exclusions=config/resource.exclusions.yaml
      - resource.customizations.useOpenLibs.apps_Deployment=config/resource.customizations.useOpenLibs.apps_Deployment
      - resource.customizations.health.apps_Deployment=resource-customizations/apps_Deployment/health.lua

  - name: argocd-notifications-cm
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - service.webhook.github=notifications/webhook.github.yaml
      - template.github-smoke-tests=notifications/template.github-smoke-tests.yaml
      - trigger.smoke-tests-on-deployed=notifications/trigger.smoke-tests-on-deployed.yaml
