apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.12
  - avp-plugin-config-cm.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
    patch: |-
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
      data:
        policy.default: role:admin

  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            automountServiceAccountToken: true
            volumes:
              - configMap:
                  name: cmp-plugin
                name: cmp-plugin
              - name: custom-tools
                emptyDir: {}
            initContainers:
            - name: download-tools
              image: registry.access.redhat.com/ubi8
              env:
                - name: AVP_VERSION
                  value: 1.11.0
              command: [sh, -c]
              args:
                - >-
                  curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
                  chmod +x argocd-vault-plugin &&
                  mv argocd-vault-plugin /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
            containers:
            - name: avp
              command: [/var/run/argocd/argocd-cmp-server]
              image: registry.access.redhat.com/ubi8
              securityContext:
                runAsNonRoot: true
                runAsUser: 999
              volumeMounts:
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /tmp
                  name: tmp

                # Register plugins into sidecar
                - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                  subPath: avp.yaml
                  name: cmp-plugin

                # Important: Mount tools into $PATH
                - name: custom-tools
                  subPath: argocd-vault-plugin
                  mountPath: /usr/local/bin/argocd-vault-plugin

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - url=config/url
      - resource.exclusions=config/resource.exclusions.yaml
      - resource.customizations.useOpenLibs.apps_Deployment=config/resource.customizations.useOpenLibs.apps_Deployment
      - resource.customizations.health.apps_Deployment=resource-customizations/apps_Deployment/health.lua

  - name: argocd-notifications-cm
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - service.webhook.github=notifications/webhook.github.yaml
      - template.github-smoke-tests=notifications/template.github-smoke-tests.yaml
      - trigger.smoke-tests-on-deployed=notifications/trigger.smoke-tests-on-deployed.yaml
